# Generated by Django 4.1.5 on 2023-01-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_test', '0002_games_delete_comp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='cathegory',
            new_name='category',
        ),
    ]
